name: day13spatial

channels:
  - conda-forge

dependencies:
  - numpy
  - pandas
  # environment for notebooks
  - ipykernel
  - jupyter
  # REST/fetching web data
  - requests
  # visualisation
  - matplotlib
  - seaborn
  # geospatial libraries
  - geopandas
  - cartopy
  - shapely
  - fiona
  - rasterio
  - descartes
